### ISSUE TITLE
Crash when using on server

### ISSUE THREAD

**Issue by vivagabe** [team-abnormals/clayworks#22] opened 2024-04-02 00:45 UTC
[crash-2024-04-01_17.38.48-fml.txt](https://github.com/team-abnormals/clayworks/files/14830062/crash-2024-04-01_17.38.48-fml.txt)

**Comment by bageldotjpg** [comment] 2024-04-02 01:13
Duplicate of #17, fixed indev

**Closed as completed by bageldotjpg** 2024-04-02 01:13 UTC
