### ISSUE TITLE
Mod Loading error when starting server

### ISSUE THREAD

**Issue by bkeller0909** [team-abnormals/clayworks#19] opened 2024-03-25 00:19 UTC
[crash-2024-03-24_19.54.21-fml.txt](https://github.com/team-abnormals/clayworks/files/14737359/crash-2024-03-24_19.54.21-fml.txt)

**Comment by bageldotjpg** [comment] 2024-03-28 14:45
Duplicate of https://github.com/team-abnormals/clayworks/issues/17

**Closed as completed by bageldotjpg** 2024-03-28 14:45 UTC
